document:
  title: "Release of Sites from Regulatory Control on Termination of Practices"
parser:
  font_decoders:
    - pdf_pages: [1, 48, 49]
      fonts: [ArialMT, Arial-BoldMT, Arial-BoldItalicMT]
      ascii_offset: 29
    - pdf_pages: [2]
      fonts: [TimesTen-Roman, TimesTen-Bold, TimesTen-Italic]
      ascii_offset: 31
