document:
  title: "Monitoring for Radioactive Material in International Mail Transported by Public Postal Operators"
parser:
  font_decoders:
    - pdf_pages: [2]
      fonts: [TimesTen-Roman, TimesTen-Bold, TimesTen-Italic]
      ascii_offset: 31
    - pdf_pages: [52]
      fonts: [ArialMT, Arial-BoldMT, Arial-BoldItalicMT]
      ascii_offset: 29
