document:
  document_id: NSS-17-T-REV1
  title: Computer Security Techniques for Nuclear Facilities
  publisher: International Atomic Energy Agency
  publication_place: Vienna
  publication_year: 2021
  series_name: IAEA Nuclear Security Series
  series_number: No. 17-T (Rev. 1)
  document_family: IAEA Nuclear Security Series
  document_category: Technical Guidance
  document_type: technical_guidance
  document_domain: nuclear_security
  document_subdomain: computer_security_for_nuclear_facilities
  sti_pub_number: STI/PUB/1921
  isbn_pdf: 978-92-0-123620-3
  language: en
parser:
  include_text_blocks: true
